name: Despliegue Cliente (AWS)
on:
  repository_dispatch:
    types: [deploy_client_infra]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CÃ³digo
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init
        env:
          # Le pasamos las llaves de AWS a Terraform
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Crear Servidor en AWS
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
            -var="client_id=${{ github.event.client_payload.CLIENT_ID }}" \
            -var="instance_size=${{ github.event.client_payload.INSTANCE_SIZE }}" \
            -var="logo_url='${{ github.event.client_payload.ENV_VARS.LOGO_URL }}'" \
            -var="industry='${{ github.event.client_payload.ENV_VARS.INDUSTRY }}'" \
            -var="welcome_msg='${{ github.event.client_payload.ENV_VARS.WELCOME_MESSAGE }}'" \
            -var="enable_payments=${{ github.event.client_payload.ENV_VARS.ENABLE_PAYMENTS }}" \
            -var="enable_vip=${{ github.event.client_payload.ENV_VARS.ENABLE_VIP_SCORING }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Obtener IP del Output
        id: get_ip
        working-directory: ./terraform
        run: |
          # Extraemos la IP limpia del output de Terraform
          SERVER_IP=$(terraform output -raw server_ip)
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV

      - name: ðŸ”” Notificar a n8n (Email)
        run: |
          curl -X POST https://dot-mineral-advancement-skirt.trycloudflare.com/webhook-test/send-credentials \
          -H "Content-Type: application/json" \
          -d '{
            "email": "${{ github.event.client_payload.CLIENT_EMAIL }}",
            "server_ip": "${{ env.SERVER_IP }}",
            "client_name": "${{ github.event.client_payload.CLIENT_ID }}"
          }'