name: Despliegue Cliente (AWS)
on:
  repository_dispatch:
    types: [deploy_client_infra]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CÃ³digo
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init
        env:
          # Le pasamos las llaves de AWS a Terraform
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Crear Servidor en AWS
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
            -var="client_id=${{ github.event.client_payload.client_id }}" \
            -var="instance_size=${{ github.event.client_payload.instance_size }}" \
            -var="welcome_msg='${{ github.event.client_payload.env_vars.WELCOME_MESSAGE }}'" \
            -var="enable_payments=${{ github.event.client_payload.env_vars.ENABLE_PAYMENTS }}" \
            -var="enable_vip=${{ github.event.client_payload.env_vars.ENABLE_VIP_SCORING }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}